module.exports = [
   [
      [
         { img: 'it_equi_weapon_1', name: { vi: '', en: '' }, color: 1, star: 1, attr: { type: 'ATT', value: 10 } },
         { img: 'it_equi_weapon_2', name: { vi: '', en: '' }, color: 1, star: 1, attr: { type: 'ATT', value: 10 } },
         { img: 'it_equi_weapon_3', name: { vi: 'Đoản kiếm sắc nét', en: 'Sharp shortsword' }, color: 2, star: 1, attr: { type: 'ATT', value: 32 } },
         { img: 'it_equi_weapon_4', name: { vi: 'Thanh kiếm Hawkeye', en: 'Hawkeye sword' }, style: { marginTop: '14px', marginLeft: '12px' }, color: 2, star: 2, attr: { type: 'ATT', value: 38 } },
         { img: 'it_equi_weapon_5', name: { vi: 'Trường đao', en: 'Horse-blade' }, color: 3, star: 1, attr: { type: 'ATT', value: 66 } },
         { img: 'it_equi_weapon_6', name: { vi: 'Chạy trong hoảng loạn', en: 'Running scared' }, color: 3, star: 2, attr: { type: 'ATT', value: 85 } },
         { img: 'it_equi_weapon_7', name: { vi: 'Anh hùng kiếm lớn', en: 'Heroism big sword' }, color: 4, star: 1, attr: { type: 'ATT', value: 168 } },
         { img: 'it_equi_weapon_8', name: { vi: 'Cạnh quyết đoán', en: 'Determined edge' }, color: 4, star: 2, attr: { type: 'ATT', value: 218 } },
         { img: 'it_equi_weapon_9', name: { vi: 'Rìu chiến bình minh', en: 'Dawn battleaxe' }, style: { marginTop: '12px', marginLeft: '4px' }, color: 4, star: 3, attr: { type: 'ATT', value: 256 } },
         { img: 'it_equi_weapon_10', name: { vi: 'Lưỡi đao màu máu', en: 'Blood color blade' }, style: { marginLeft: '4px' }, color: 5, star: 1, attr: { type: 'ATT', value: 414 } },
         { img: 'it_equi_weapon_11', name: { vi: 'Anh hùng kiếm thẳng', en: 'Hero straight sword' }, style: { marginTop: '10px', marginLeft: '11px' }, color: 5, star: 2, attr: { type: 'ATT', value: 502 } },
         { img: 'it_equi_weapon_12', name: { vi: 'Thanh kiếm âm thanh', en: 'Sound Sword' }, color: 5, star: 3, attr: { type: 'ATT', value: 590 } },
         { img: 'it_equi_weapon_13', name: { vi: 'Ma kiếm', en: 'Evil Sword' }, style: { marginTop: '10px', marginLeft: '4px' }, color: 5, star: 4, attr: { type: 'ATT', value: 678 } },
         { img: 'it_equi_weapon_14', name: { vi: 'Huyền thoại kiếm lửa', en: 'Legend fire sword' }, color: 6, star: 1, attr: { type: 'ATT', value: 914 } },
         { img: 'it_equi_weapon_15', name: { vi: 'Kiếm Warth hạng nhất', en: 'First-class warth sword' }, color: 6, star: 2, attr: { type: 'ATT', value: 1116 } },
         { img: 'it_equi_weapon_16', name: { vi: 'Thanh kiếm vô song', en: 'Peerless Blissful Sword' }, color: 6, star: 3, attr: { type: 'ATT', value: 1317 } },
         { img: 'it_equi_weapon_17', name: { vi: 'Trận chiến vĩnh cửu', en: 'Eternal battle' }, color: 6, star: 4, attr: { type: 'ATT', value: 1519 } },
      ], [
         { img: 'it_equi_armor_1', name: { vi: '', en: '' }, color: 1, star: 0, attr: { type: 'HP', value: 50 }, style: { marginTop: '13px' } },
         { img: 'it_equi_armor_2', name: { vi: '', en: '' }, color: 1, star: 0, style: { marginTop: '17px', marginLeft: '6px' }, attr: { type: 'HP', value: 50 } },
         { img: 'it_equi_armor_3', name: { vi: 'DEF chính thức', en: 'Offical DEF' }, style: { marginTop: '7px', marginLeft: '17px' }, color: 2, star: 1, attr: { type: 'HP', value: 141 } },
         { img: 'it_equi_armor_4', name: { vi: 'Giáp chim ưng', en: 'Hawk armor' }, style: { marginTop: '15px' }, color: 2, star: 2, attr: { type: 'HP', value: 169 } },
         { img: 'it_equi_armor_5', name: { vi: 'Tinh thần hiệp sĩ', en: 'Knight spirit' }, color: 3, star: 1, attr: { type: 'HP', value: 337 } },
         { img: 'it_equi_armor_6', name: { vi: 'DEF dũng cảm', en: 'Brave DEF' }, color: 3, star: 2, attr: { type: 'HP', value: 434 } },
         { img: 'it_equi_armor_7', name: { vi: 'DEF cứng', en: 'Generous hard DEF' }, color: 4, star: 1, attr: { type: 'HP', value: 970 } },
         { img: 'it_equi_armor_8', name: { vi: 'DEF quái thú', en: 'Beast DEF' }, color: 4, star: 2, attr: { type: 'HP', value: 1255 } },
         { img: 'it_equi_armor_9', name: { vi: 'Áo giáp bình minh', en: 'Dawn Corselet' }, style: { marginTop: '5px', transform: 'scale(.8)' }, color: 4, star: 3, attr: { type: 'HP', value: 1541 } },
         { img: 'it_equi_armor_10', name: { vi: 'Sợ máu', en: 'Blood fear' }, style: { transform: 'scale(.8)', marginLeft: '3px' }, color: 5, star: 1, attr: { type: 'HP', value: 2645 } },
         { img: 'it_equi_armor_11', name: { vi: 'Áo giáp Anh hùng', en: 'Hero armour' }, color: 5, star: 2, attr: { type: 'HP', value: 3207 } },
         { img: 'it_equi_armor_12', name: { vi: 'Áo giáp âm thanh', en: 'Sound Corselet' }, color: 5, star: 3, attr: { type: 'HP', value: 3770 } },
         { img: 'it_equi_armor_13', name: { vi: 'Ma giáp', en: 'Evil Corselet' }, color: 5, star: 4, attr: { type: 'HP', value: 4333 } },
         { img: 'it_equi_armor_14', name: { vi: 'DEF Truyền thuyết công đức', en: 'Legend merit DEF' }, style: { marginLeft: '4px' }, color: 6, star: 1, attr: { type: 'HP', value: 6401 } },
         { img: 'it_equi_armor_15', name: { vi: 'DEF ý chí hạng nhất', en: 'First-class will DEF' }, style: { marginTop: '2px', marginLeft: '6px' }, color: 6, star: 2, attr: { type: 'HP', value: 7811 } },
         { img: 'it_equi_armor_16', name: { vi: 'DEF vô hạn kiềm chế', en: 'Matchless restrain DEF' }, style: { marginTop: '4px' }, color: 6, star: 3, attr: { type: 'HP', value: 9222 } },
         { img: 'it_equi_armor_17', name: { vi: 'Bảo vệ vĩnh cửu', en: 'Eternal guard' }, style: { marginTop: '3px', transform: 'scale(.85)' }, color: 6, star: 4, attr: { type: 'HP', value: 10632 } },

      ], [
         { img: 'it_equi_access_1', name: { vi: '', en: '' }, color: 1, star: 0, style: { marginTop: '13px', marginLeft: '12px' }, attr: { type: 'ATT', value: 0 } },
         { img: 'it_equi_access_2', name: { vi: '', en: '' }, color: 1, star: 1, style: { marginTop: '12px', marginLeft: '12px' }, attr: { type: 'ATT', value: 0 } },
         { img: 'it_equi_access_3', name: { vi: 'Vòng tay cứng', en: 'Hard cuff' }, style: { marginTop: '10px', marginLeft: '13px' }, color: 2, star: 1, attr: { type: 'ATT', value: 21 } },
         { img: 'it_equi_access_4', name: { vi: 'Vòng tay cảnh giác', en: 'Alertness cuff' }, style: { marginTop: '10px', marginLeft: '13px' }, color: 2, star: 2, attr: { type: 'ATT', value: 25 } },
         { img: 'it_equi_access_5', name: { vi: 'Vòng tay hiệp sĩ', en: 'Knight cuff' }, style: { marginTop: '15px', marginLeft: '15px', transform: 'unset' }, color: 3, star: 1, attr: { type: 'ATT', value: 44 } },
         { img: 'it_equi_access_6', name: { vi: 'Vòng tay dũng cảm', en: 'Brave cuff' }, style: { marginTop: '15px', marginLeft: '15px', transform: 'unset' }, color: 3, star: 2, attr: { type: 'ATT', value: 57 } },
         { img: 'it_equi_access_7', name: { vi: 'Vòng tay năng lượng', en: 'Energetically cuff' }, style: { marginTop: '17px', marginLeft: '15px', transform: 'unset' }, color: 4, star: 1, attr: { type: 'ATT', value: 122 } },
         { img: 'it_equi_access_8', name: { vi: 'Vòng ttay răng sắc nhọn', en: 'Sharp tooth cuff' }, style: { marginTop: '15px', marginLeft: '15px', transform: 'unset' }, color: 4, star: 2, attr: { type: 'ATT', value: 145 } },
         { img: 'it_equi_access_9', name: { vi: 'Xích vàng bình minh', en: 'Dawn Golden Chain' }, style: { marginTop: '11px', marginLeft: '5px' }, color: 4, star: 3, attr: { type: 'ATT', value: 178 } },
         { img: 'it_equi_access_10', name: { vi: 'Cảnh báo máu', en: 'Blood warning' }, style: { marginTop: '19px', marginLeft: '18px', transform: 'unset' }, color: 5, star: 1, attr: { type: 'ATT', value: 276 } },
         { img: 'it_equi_access_11', name: { vi: 'Anh hùng mặt trăng', en: 'Hero moon' }, style: { marginTop: '14px', marginLeft: '16px', transform: 'unset' }, color: 5, star: 2, attr: { type: 'ATT', value: 335 } },
         { img: 'it_equi_access_12', name: { vi: 'Cờ chiến âm thanh', en: 'Sound War Chess' }, style: { marginTop: '10px', marginLeft: '16px', transform: 'unset' }, color: 5, star: 3, attr: { type: 'ATT', value: 393 } },
         { img: 'it_equi_access_13', name: { vi: 'Quỷ khiên', en: 'Evil Shield' }, style: { marginLeft: '5px' }, color: 5, star: 4, attr: { type: 'ATT', value: 452 } },
         { img: 'it_equi_access_14', name: { vi: 'Hoa tai huyền thoại', en: 'Legend pendant' }, style: { marginTop: '15px', marginLeft: '10px', transform: 'unset' }, color: 6, star: 1, attr: { type: 'ATT', value: 610 } },
         { img: 'it_equi_access_15', name: { vi: 'Khiên chắn bảo vệ hạng nhất', en: 'First-class guard shield' }, color: 6, star: 2, attr: { type: 'ATT', value: 744 } },
         { img: 'it_equi_access_16', name: { vi: 'Thánh giá vô song', en: 'Matchless cross' }, style: { transform: 'unset' }, color: 6, star: 3, attr: { type: 'ATT', value: 878 } },
         { img: 'it_equi_access_17', name: { vi: 'Cánh vĩnh cửu', en: 'Eternal wing' }, style: { marginTop: '14px', marginLeft: '9px' }, color: 6, star: 4, attr: { type: 'ATT', value: 1013 } }
      ], [
         { img: 'it_equi_shoes_1', name: { vi: '', en: '' }, color: 1, star: 1, style: { marginTop: '12px', marginLeft: '10px' }, attr: { type: 'HP', value: 0 } },
         { img: 'it_equi_shoes_2', name: { vi: '', en: '' }, color: 1, star: 1, style: { marginTop: '12px', marginLeft: '10px' }, attr: { type: 'HP', value: 0 } },
         { img: 'it_equi_shoes_3', name: { vi: 'Mũ sát thủ', en: 'Assassin hood' }, style: { marginTop: '15px', marginLeft: '13px' }, color: 2, star: 1, attr: { type: 'HP', value: 94 } },
         { img: 'it_equi_shoes_4', name: { vi: 'Mũ sắt', en: 'Sharp hood' }, color: 2, star: 2, attr: { type: 'HP', value: 113 } },
         { img: 'it_equi_shoes_5', name: { vi: 'Mũ hiệp sĩ', en: 'Knight helmet' }, color: 3, star: 1, attr: { type: 'HP', value: 223 } },
         { img: 'it_equi_shoes_6', name: { vi: 'Mũ tiên phong', en: 'Pioneer helmet' }, color: 3, star: 2, attr: { type: 'HP', value: 289 } },
         { img: 'it_equi_shoes_7', name: { vi: 'Mũ Bull', en: 'Bull helmet' }, color: 4, star: 1, attr: { type: 'HP', value: 647 } },
         { img: 'it_equi_shoes_8', name: { vi: 'Mũ dữ dội', en: 'Fierceness helmet' }, color: 4, star: 2, attr: { type: 'HP', value: 837 } },
         { img: 'it_equi_shoes_9', name: { vi: 'Mũ bình minh', en: 'Dawn Helmet' }, style: { marginLeft: '20px' }, color: 4, star: 3, attr: { type: 'HP', value: 1027 } },
         { img: 'it_equi_shoes_10', name: { vi: 'Áo giáp máu', en: 'Blood armour' }, style: { marginTop: '12px' }, color: 5, star: 1, attr: { type: 'HP', value: 1763 } },
         { img: 'it_equi_shoes_11', name: { vi: 'Mũ anh hùng', en: 'Hero helmet' }, style: { marginTop: '15px' }, color: 5, star: 2, attr: { type: 'HP', value: 2183 } },
         { img: 'it_equi_shoes_12', name: { vi: 'Mũ âm thanh', en: 'Sound Helmet' }, color: 5, star: 3, attr: { type: 'HP', value: 2513 } },
         { img: 'it_equi_shoes_13', name: { vi: 'Mũ ác quỷ', en: 'Evil Helmet' }, color: 5, star: 4, attr: { type: 'HP', value: 2889 } },
         { img: 'it_equi_shoes_14', name: { vi: 'Mũ huyền thoại', en: 'Legend helmet' }, style: { marginTop: '13px' }, color: 6, star: 1, attr: { type: 'HP', value: 4267 } },
         { img: 'it_equi_shoes_15', name: { vi: 'Mũ niềm tin hạng nhất', en: 'First-class belief helmet' }, style: { marginTop: '11px' }, color: 6, star: 2, attr: { type: 'HP', value: 5207 } },
         { img: 'it_equi_shoes_16', name: { vi: 'Mũ niềm tin vô song', en: 'Matchless belief helmet' }, style: { marginTop: '11px', marginLeft: '4px' }, color: 6, star: 3, attr: { type: 'HP', value: 6148 } },
         { img: 'it_equi_shoes_17', name: { vi: 'Ý nghĩa vĩnh cửu', en: 'Eternal meaning' }, style: { marginLeft: '6px' }, color: 6, star: 4, attr: { type: 'HP', value: 7088 } },

      ]
   ], {
      43: { name: { vi: 'Giáp Tân thủ', en: 'Dawn suit' }, attr: [{ type: 'HP', value: 2, unit: '%' }, { type: 'ATT', value: 3, unit: '%' }, { type: 'HP', value: 1, unit: '%' }] },
      51: { name: { vi: 'Giáp Vàng', en: 'Gold suit' }, attr: [{ type: 'HP', value: 4, unit: '%' }, { type: 'ATT', value: 5, unit: '%' }, { type: 'HP', value: 2, unit: '%' }] },
      52: { name: { vi: 'Giáp Bão tố', en: 'Storm wind suit' }, attr: [{ type: 'HP', value: 5, unit: '%' }, { type: 'ATT', value: 7, unit: '%' }, { type: 'HP', value: 4, unit: '%' }] },
      53: { name: { vi: 'Giáp Hồn ma lang thang', en: 'Wandering ghost suit' }, attr: [{ type: 'HP', value: 7, unit: '%' }, { type: 'ATT', value: 9, unit: '%' }, { type: 'HP', value: 4, unit: '%' }] },
      54: { name: { vi: 'Giáp Máu', en: 'HP suit' }, attr: [{ type: 'HP', value: 8, unit: '%' }, { type: 'ATT', value: 11, unit: '%' }, { type: 'HP', value: 5, unit: '%' }] },
      61: { name: { vi: 'Giáp Lửa', en: 'Flames suit' }, attr: [{ type: 'HP', value: 10, unit: '%' }, { type: 'ATT', value: 13, unit: '%' }, { type: 'HP', value: 5, unit: '%' }] },
      62: { name: { vi: 'Giáp Hoàng đế', en: 'Emperor suit' }, attr: [{ type: 'HP', value: 11, unit: '%' }, { type: 'ATT', value: 15, unit: '%' }, { type: 'HP', value: 6, unit: '%' }] },
      63: { name: { vi: 'Giáp Tử thần', en: 'Death suit' }, attr: [{ type: 'HP', value: 12, unit: '%' }, { type: 'ATT', value: 17, unit: '%' }, { type: 'HP', value: 7, unit: '%' }] },
      64: { name: { vi: 'Giáp Thánh', en: 'Saint suit' }, attr: [{ type: 'HP', value: 14, unit: '%' }, { type: 'ATT', value: 19, unit: '%' }, { type: 'HP', value: 7, unit: '%' }] }
   }

]